services:

  teable:
    image: ghcr.io/teableio/teable:latest
    container_name: teable
    restart: unless-stopped
    ports:
      - '7880:3000'
    volumes:
      - ./teable-data:/app/.assets:rw
    env_file:
      - .env
    environment:
      - TZ=America/Costa_Rica
      - NEXT_ENV_IMAGES_ALL_REMOTE=true
    depends_on:
      teable-db-migrate:
        condition: service_completed_successfully

  teable-db:
    image: postgres:15.4
    container_name: teable-db
    restart: unless-stopped
    ports:
      - '42345:5432'
    volumes:
      - ./teable-db:/var/lib/postgresql/data:rw
    environment:
      - TZ=Europe/Madrid
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: ['CMD-SHELL', "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 10s
      timeout: 3s
      retries: 3

  teable-db-migrate:
    image: ghcr.io/teableio/teable-db-migrate:latest
    container_name: teable-migrate
    environment:
      - TZ=Europe/Madrid
      - PRISMA_DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    depends_on:
      teable-db:
        condition: service_healthy
